### ISSUE TITLE
database query error-bug in the software

### ISSUE THREAD

**Issue by S6savahd** [EIS-Bonn/OpenResearch#1]
creating a new article resulted in the following output:

Notice: Array to string conversion in /srv/www/openresearch/includes/db/Database.php on line 2192

Notice: Array to string conversion in /srv/www/openresearch/includes/db/Database.php on line 2192

Notice: Array to string conversion in /srv/www/openresearch/includes/db/Database.php on line 2192

Notice: Array to string conversion in /srv/www/openresearch/includes/db/Database.php on line 2192
A database query error has occurred. This may indicate a bug in the software.

Query:
SELECT 1 FROM `page` WHERE (Array) OR (Array) OR (Array) OR (Array) LIMIT 1
Function: ApiStashEdit::checkCache
Error: 1054 Unknown column 'Array' in 'where clause' (localhost)

**Comment by S6savahd** [comment]
temporarily solved by removing WikiEdits extensions, let's see if this solves it completely.

**Comment by white-gecko** [comment]
Unfortunately removing the WikiEdits didn't solve this problem, I just got the same error.

This is the content of the page I've tried to create:

```
{{Event
 | Acronym = CIKM 2016
 | Title = ACM International Conference on Information and Knowledge Management
 | Type = Conference
 | Series = CIKM
 | Field = Information and Knowledge Management
 | Homepage = http://www.cikm2016.org/
 | Start date = Oct 24, 2016
 | End date =  Oct 28, 2016
 | City= Indianapolis
 | State =  IN
 | Country =  USA
 | Abstract deadline = May 09, 2016
 | Submission deadline = May 16, 2016
 | Notification = Jul 18, 2016
 | Camera ready = Aug 15, 2016
}}
```

Unfortunately I don't know a solution for this.

**Comment by liyakun** [comment]
@white-gecko, thanks for reporting the bug, and it was discussed in https://phabricator.wikimedia.org/T105597, I used the method proposed by the Mark A. Hershberger's comment temporarily.

**Comment by white-gecko** [comment]
Ok, so it works now with the example as posted above, the thing is, that URLs should not contain the protocoal it is prepended automatically with `http://`. But this will not work if you want to refer to a `https://` URL.

I had to replace

     | Homepage = http://www.cikm2016.org/

by

     | Homepage = www.cikm2016.org
