### ISSUE TITLE
Improvement for the event pages regarding the twitter link

### ISSUE THREAD

**Issue by Rebazinho** [EIS-Bonn/OpenResearch#13]
Right now when an event page is created there will be an automatically generated link to twitter (even if the user doesn't want to link a twitter acount). The problem is the link leads to a non-existing twitter page.

I am not sure about an actual solution, but I would suggest to handle it like this:
- If the field for a twitter account is empty there should be no link in the event page shown
- If the field is filled though there should be the related link shown in the event page

@liyakun Sahar told me to tag you mate

**Comment by liyakun** [comment]
@Rebazinho thanks for pointing it out, it is improved. You can see event page [ICDPR_2017](http://openresearch.org/ICDPR_2017) and [KDK_2017](http://openresearch.org/KDK_2017).
