### ISSUE TITLE
Strange properties

### ISSUE THREAD

**Issue by white-gecko** [EIS-Bonn/OpenResearch#4]
There are strange properties, such as

    2011/02/ {| cellspacing="0" cellpadding="5" style="position:relative; margin: 0 0 0.5em 1em; border-collapse: collapse; border: 1px solid #aaa; background: #fff; float: right; clear: right; width: 20em" ! colspan="2" style="background: #A0A0A0; color: whi (0)

in http://openresearch.org/index.php?title=Special:Properties&limit=500&offset=0

I think they should be removed somehow.

**Comment by liyakun** [comment]
@white-gecko  these are removed.

**Comment by liyakun** [comment]
I created another issue for other [property mistakes](https://github.com/EIS-Bonn/OpenResearch/issues/7). If you think this issue is solved, please close it.
